### ISSUE TITLE
Änderungsvorschlag: Benennung des Kalendereintrages

### ISSUE THREAD

**Issue by vcdwelt** [JohnDOEbug/anniversariesGoogleCalendar#1]
Zwar kein Bug, aber wusste nicht wie ich das sonst melden könnte :-)

Kann man ändern, dass vor jeden Eintrag "Birthday:" gesetzt wird, sondern einfach nur der Name des Kontaktes eingetragen wird?

**Comment by vcdwelt** [comment]
Habe es selbst gefunden, war dann doch ziemlich einfach :)

Zeile 130:
title: "Birthday: " + name,
ändern in:
title: name,

Danke für das geniale Script!

**Comment by JohnDOEbug** [comment]
Jop, genau so! :-)
Danke!

**Comment by JohnDOEbug** [comment]
Ja, genau, das wäre ein schneller Fix. Allerdings wird die Funktion `compareAndSyncEvents` dadurch nicht mehr ganz korrekt arbeiten, insbesondere wenn andere Jubiläen ohne Label in einem Kontakt hinterlegt sind. Deiner Frage nach gehe ich davon aus, dass du lediglich Geburtstage in deinem Kalender haben möchtest. In diesem Fall empfehle ich dir, auch die Funktion `getAllContactsEvents` so anzupassen, dass nur Geburtstage berücksichtigt werden. Dazu könntest du einfach die Zeilen 138–150 (inklusive) löschen.

Es freut mich, dass dir das Skript gefällt! :-)

**Comment by vcdwelt** [comment]
Scheinbar funktioniert der Rest auch mit meiner Änderung :) Habe auch andere Termine die ich hinterlegt habe korrekt im Kalender stehen. 
Aber werde den Hinweis im Hinterkopf behalten, falls doch mal etwas schief gehen sollte!

Das Script ist echt ein Retter in der Not, war schon kurz davor unseren kompletten Familienkalender zu Microsoft umzuziehen :-D
